### ISSUE TITLE
ECMenuMorph fades out when its parent abandons

### ISSUE THREAD

**Issue by LinqLover** [MrModder/Autocompletion#19]
Scenario:
- Open a workspace window
- Start typing something, Autocompletion menu will appear
- Close the workspace window

Now, the Autocompletion menu slowly fades out. However, as it parent has abandoned, I would expect it to abandon immediately.

**Comment by LeonMatthes** [comment]
Should be fixed now

I actually added the fading of the MenuMorph because I did not know how to find out whether the window is still there, and the Autocompletion would otherwise stay open forever.
But now I found a way to check for the containing window.
The fix is not great however, because it no longer allows to open Autocompletion in any model that does not have a window...

**Comment by LeonMatthes** [comment]
> The fix is not great however, because it no longer allows to open Autocompletion in any model that does not have a window...

Fixed by allowing the model to decide for itself whether to close the Autocompletion
