### ISSUE TITLE
Cannot revert to OCompletion

### ISSUE THREAD

**Issue by LinqLover** [MrModder/Autocompletion#24]
Scenario:
- Go to Preferences and disable the option #useECompletionInsteadOfOCompletion
- Open a new workspace window
- Type one character into it

Bug:
- MessageNotUnderstood: #currentMenuMorph in ECController returns nil

(Not that I wanted to turn my back on Autocompletion, but I wanted to test downward compatibility of our tool for users who have not yet had the pleasure of this cool package!)

**Comment by LeonMatthes** [comment]
I'm currently thinking it is best to move the Autocompletion code to its own prefix (so AController, instead of OController/ECController, etc.)
This would allow O/eCompletion to exist separately from the Autocompletion, rendering this option useless anyway.
This is however challenging when it comes to extensions that have been made, which would mean the model API to use Autocompletion would have to stay compatible with eCompletion/OCompletion.
But that means this issue is not really high on my list of priorities right now, feel free to open a PR if you know how to fix it though.

**Comment by LeonMatthes** [comment]
Reverting to oCompletion is no longer supported.

**Comment by LinqLover** [comment]
In this case the preference `#useECompletionInsteadOfOCompletion` should probably be removed or deprecated, shouldn't it? :)

**Comment by LeonMatthes** [comment]
It is removed.
Not entirely sure if Metacello will update this correctly though.
