### ISSUE TITLE
Fading out transparency is rendered wrong in dark UI themes

### ISSUE THREAD

**Issue by LinqLover** [MrModder/Autocompletion#41]
![image](https://user-images.githubusercontent.com/38782922/141849807-6ab52f52-0e86-42b8-b13f-4fefa15031c2.png)

Whereas in light themes:

![image](https://user-images.githubusercontent.com/38782922/141849919-b965ef9e-935e-41ef-a091-6c578d7ecee1.png)

**Comment by LeonMatthes** [comment]
It does seem like your text is fading though, right?
I've had issues with the Trim theme that had a font that couldn't be rendered with transparency. But this seems unrelated.

This might be an artifact of human perception, where it seems like the text is fading slower with white on dark, instead of black on white.

Could maybe be fixed by passing the opacity of the text through some transform function, maybe squaring it will do, so that it fades faster.

**Comment by LinqLover** [comment]
> I've had issues with the Trim theme that had a font that couldn't be rendered with transparency. But this seems unrelated.

> This might be an artifact of human perception

Not so sure, let's watch the timelapse:

![Autocompletion#41-timelapse](https://user-images.githubusercontent.com/38782922/143720887-c4621557-a87c-4741-8e7a-60c3dfa77bf0.gif)

**Comment by LeonMatthes** [comment]
Yeah, that seems just as buggy as with the Trim theme.

You're using Solarized (dark), right?

**Comment by LeonMatthes** [comment]
IIRC this was an issue with the font, I'm not really sure I can do anything about that.

**Comment by LeonMatthes** [comment]
Yup, seems to be an issue with TrueType fonts, StrikeFonts fade nicely :thinking: 

This is therefore rather a problem with the Squeak font rendering on an AlphaBlendingCanvas, than an issue with Autocompletion.

Please open an issue on the Squeak forum for this problem.
